# Generated by Django 6.0.5 on 2026-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
