# Generated by Django 6.0.5 on 2026-06-09 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='notice',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assignments_completed',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='student',
            name='coding_hours_per_week',
            field=models.FloatField(default=10.0, help_text='Average coding hours per week'),
        ),
        migrations.AddField(
            model_name='student',
            name='communication_score',
            field=models.IntegerField(default=5, help_text='Communication skill rating (1-10)'),
        ),
        migrations.AddField(
            model_name='student',
            name='dream_company',
            field=models.CharField(default='Google', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stress_rating',
            field=models.IntegerField(default=5, help_text='Self-reported stress level (1-10)'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_hours_per_day',
            field=models.FloatField(default=3.0, help_text='Average study hours per day'),
        ),
        migrations.AddField(
            model_name='student',
            name='target_cgpa',
            field=models.FloatField(default=8.5),
        ),
        migrations.AddField(
            model_name='student',
            name='target_package',
            field=models.FloatField(default=12.0, help_text='Target placement package in LPA'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_assignments',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='home.student'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(help_text='Marks obtained'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='home.student'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
